# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

hostname: vccw.local
ip: 192.168.33.99
multisite: true
plugins:
  - dynamic-hostname
  - wp-total-hacks
  - tinymce-templates
  - theme-check
  - wordpress-importer
linked_clone: true
